using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class AircraftForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtModel, txtCapacity, txtManufacturer;
        private ComboBox cmbAirline;

        public AircraftForm()
        {
            FormTheme.Apply(this, "Manage Aircraft");
            this.Size = new Size(780, 520);
            this.Controls.Add(FormTheme.MakeHeaderPanel("🛩 Aircraft", "Manage the fleet of aircraft", this.Width));

            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 740, 220);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            int lx = 15, fx = 130, lx2 = 430, fx2 = 545, y = 315;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Model:", lx, y));
            txtModel = FormTheme.MakeTextBox(fx, y); this.Controls.Add(txtModel);
            this.Controls.Add(FormTheme.MakeLabel("Manufacturer:", lx2, y));
            txtManufacturer = FormTheme.MakeTextBox(fx2, y, 200); this.Controls.Add(txtManufacturer);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Capacity:", lx, y));
            txtCapacity = FormTheme.MakeTextBox(fx, y, 90); this.Controls.Add(txtCapacity);
            this.Controls.Add(FormTheme.MakeLabel("Airline:", lx2, y));
            cmbAirline = FormTheme.MakeComboBox(fx2, y, 160);
            this.Controls.Add(cmbAirline);

            y += 50;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try
            {
                dgv.DataSource = dbHelper.ExecuteQuery("SELECT a.*, al.Name AS AirlineName FROM Aircraft a JOIN Airline al ON a.AirlineID = al.AirlineID");
                if (dgv.Columns.Contains("AircraftID")) dgv.Columns["AircraftID"].Visible = false;
                if (dgv.Columns.Contains("AirlineID")) dgv.Columns["AirlineID"].Visible = false;

                DataTable dtAirlines = dbHelper.ExecuteQuery("SELECT AirlineID, Name FROM Airline");
                cmbAirline.DataSource = dtAirlines;
                cmbAirline.DisplayMember = "Name";
                cmbAirline.ValueMember = "AirlineID";
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["AircraftID"]?.Value?.ToString();
            txtModel.Text = row.Cells["Model"]?.Value?.ToString();
            txtManufacturer.Text = row.Cells["Manufacturer"]?.Value?.ToString();
            txtCapacity.Text = row.Cells["Capacity"]?.Value?.ToString();
            cmbAirline.SelectedValue = row.Cells["AirlineID"]?.Value;
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Aircraft (Model, Capacity, Manufacturer, AirlineID) VALUES ('{txtModel.Text}',{txtCapacity.Text},'{txtManufacturer.Text}',{cmbAirline.SelectedValue})";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Aircraft added.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Aircraft SET Model='{txtModel.Text}', Capacity={txtCapacity.Text}, Manufacturer='{txtManufacturer.Text}', AirlineID={cmbAirline.SelectedValue} WHERE AircraftID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Aircraft updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this aircraft?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Aircraft WHERE AircraftID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields() { txtId.Clear(); txtModel.Clear(); txtCapacity.Clear(); txtManufacturer.Clear(); if (cmbAirline.Items.Count > 0) cmbAirline.SelectedIndex = 0; }
    }
}
