using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class AirlineForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtCode, txtName, txtCity, txtCountry;

        public AirlineForm()
        {
            FormTheme.Apply(this, "Manage Airlines");
            this.Size = new Size(780, 520);

            this.Controls.Add(FormTheme.MakeHeaderPanel("🛫 Airlines", "Manage airline carriers", this.Width));

            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 740, 220);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            int lx = 15, fx = 130, lx2 = 430, fx2 = 545, y = 315;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Code:", lx, y));
            txtCode = FormTheme.MakeTextBox(fx, y, 90); this.Controls.Add(txtCode);
            this.Controls.Add(FormTheme.MakeLabel("Name:", lx2, y));
            txtName = FormTheme.MakeTextBox(fx2, y, 200); this.Controls.Add(txtName);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("City:", lx, y));
            txtCity = FormTheme.MakeTextBox(fx, y); this.Controls.Add(txtCity);
            this.Controls.Add(FormTheme.MakeLabel("Country:", lx2, y));
            txtCountry = FormTheme.MakeTextBox(fx2, y); this.Controls.Add(txtCountry);

            y += 50;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try { 
                dgv.DataSource = dbHelper.ExecuteQuery("SELECT * FROM Airline"); 
                if (dgv.Columns.Contains("AirlineID")) dgv.Columns["AirlineID"].Visible = false;
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["AirlineID"]?.Value?.ToString();
            txtCode.Text = row.Cells["Code"]?.Value?.ToString();
            txtName.Text = row.Cells["Name"]?.Value?.ToString();
            txtCity.Text = row.Cells["City"]?.Value?.ToString();
            txtCountry.Text = row.Cells["Country"]?.Value?.ToString();
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Airline (Name, City, Country, Code) VALUES ('{txtName.Text}','{txtCity.Text}','{txtCountry.Text}','{txtCode.Text}')";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Airline added.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Airline SET Name='{txtName.Text}', City='{txtCity.Text}', Country='{txtCountry.Text}', Code='{txtCode.Text}' WHERE AirlineID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Airline updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this airline?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Airline WHERE AirlineID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields() { txtId.Clear(); txtCode.Clear(); txtName.Clear(); txtCity.Clear(); txtCountry.Clear(); }
    }
}
