using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class BookingForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtTotalAmount;
        private ComboBox cmbPassenger;
        private DateTimePicker dtpBookingDate;
        private ComboBox cmbStatus;

        public BookingForm()
        {
            FormTheme.Apply(this, "Manage Bookings");
            this.Size = new Size(820, 530);

            this.Controls.Add(FormTheme.MakeHeaderPanel("📋 Bookings", "Manage passenger flight bookings", this.Width));

            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 780, 220);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            int lx = 15, fx = 130, lx2 = 450, fx2 = 565, y = 315;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Passenger:", lx, y));
            cmbPassenger = FormTheme.MakeComboBox(fx, y, 160);
            this.Controls.Add(cmbPassenger);
            this.Controls.Add(FormTheme.MakeLabel("Booking Date:", lx2, y));
            dtpBookingDate = FormTheme.MakeDatePicker(fx2, y, 180); this.Controls.Add(dtpBookingDate);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Total Amount:", lx, y));
            txtTotalAmount = FormTheme.MakeTextBox(fx, y, 120); this.Controls.Add(txtTotalAmount);
            this.Controls.Add(FormTheme.MakeLabel("Status:", lx2, y));
            cmbStatus = FormTheme.MakeComboBox(fx2, y, 160);
            cmbStatus.Items.AddRange(new string[] { "Confirmed", "Pending", "Cancelled" });
            cmbStatus.SelectedIndex = 0;
            this.Controls.Add(cmbStatus);

            y += 50;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try
            {
                dgv.DataSource = dbHelper.ExecuteQuery(
                    "SELECT b.BookingID, b.Booking_date, b.Status, b.Totalamount, b.PassengerID, " +
                    "p.first_name + ' ' + p.Last_name AS PassengerName " +
                    "FROM Booking b JOIN Passenger p ON b.PassengerID = p.PassengerID");
                if (dgv.Columns.Contains("BookingID")) dgv.Columns["BookingID"].Visible = false;
                if (dgv.Columns.Contains("PassengerID")) dgv.Columns["PassengerID"].Visible = false;

                DataTable dtPassengers = dbHelper.ExecuteQuery("SELECT PassengerID, first_name + ' ' + Last_name AS Name FROM Passenger");
                cmbPassenger.DataSource = dtPassengers;
                cmbPassenger.DisplayMember = "Name";
                cmbPassenger.ValueMember = "PassengerID";
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["BookingID"]?.Value?.ToString();
            txtTotalAmount.Text = row.Cells["Totalamount"]?.Value?.ToString();
            cmbStatus.Text = row.Cells["Status"]?.Value?.ToString();
            cmbPassenger.SelectedValue = row.Cells["PassengerID"]?.Value;
            try { dtpBookingDate.Value = Convert.ToDateTime(row.Cells["Booking_date"]?.Value); } catch { }
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Booking (Booking_date, Status, Totalamount, PassengerID) " +
                           $"VALUES ('{dtpBookingDate.Value:yyyy-MM-dd}','{cmbStatus.Text}',{txtTotalAmount.Text},{cmbPassenger.SelectedValue})";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Booking added.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Booking SET Booking_date='{dtpBookingDate.Value:yyyy-MM-dd}', Status='{cmbStatus.Text}', Totalamount={txtTotalAmount.Text}, PassengerID={cmbPassenger.SelectedValue} WHERE BookingID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Booking updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this booking?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Booking WHERE BookingID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields() { txtId.Clear(); txtTotalAmount.Clear(); cmbStatus.SelectedIndex = 0; if(cmbPassenger.Items.Count > 0) cmbPassenger.SelectedIndex = 0; dtpBookingDate.Value = DateTime.Today; }
    }
}
