using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class FlightForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtFlightNumber;
        private ComboBox cmbAircraft, cmbAirline, cmbDepAirport, cmbArrAirport;
        private DateTimePicker dtpDeparture, dtpArrival;
        private ComboBox cmbStatus;

        public FlightForm()
        {
            FormTheme.Apply(this, "Manage Flights");
            this.Size = new Size(860, 600);

            this.Controls.Add(FormTheme.MakeHeaderPanel("✈ Flights", "Schedule and manage airline flights", this.Width));

            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 820, 220);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            int lx = 15, fx = 130, lx2 = 450, fx2 = 565, y = 315;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Flight No:", lx, y));
            txtFlightNumber = FormTheme.MakeTextBox(fx, y, 150); this.Controls.Add(txtFlightNumber);
            this.Controls.Add(FormTheme.MakeLabel("Status:", lx2, y));
            cmbStatus = FormTheme.MakeComboBox(fx2, y, 160);
            cmbStatus.Items.AddRange(new string[] { "Scheduled", "Delayed", "Cancelled", "Completed" });
            cmbStatus.SelectedIndex = 0;
            this.Controls.Add(cmbStatus);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Departure Time:", lx, y));
            dtpDeparture = FormTheme.MakeDatePicker(fx, y, 200); this.Controls.Add(dtpDeparture);
            this.Controls.Add(FormTheme.MakeLabel("Arrival Time:", lx2, y));
            dtpArrival = FormTheme.MakeDatePicker(fx2, y, 200); this.Controls.Add(dtpArrival);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Aircraft:", lx, y));
            cmbAircraft = FormTheme.MakeComboBox(fx, y, 160); this.Controls.Add(cmbAircraft);
            this.Controls.Add(FormTheme.MakeLabel("Airline:", lx2, y));
            cmbAirline = FormTheme.MakeComboBox(fx2, y, 160); this.Controls.Add(cmbAirline);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Dep. Airport:", lx, y));
            cmbDepAirport = FormTheme.MakeComboBox(fx, y, 160); this.Controls.Add(cmbDepAirport);
            this.Controls.Add(FormTheme.MakeLabel("Arr. Airport:", lx2, y));
            cmbArrAirport = FormTheme.MakeComboBox(fx2, y, 160); this.Controls.Add(cmbArrAirport);

            y += 48;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try
            {
                dgv.DataSource = dbHelper.ExecuteQuery(
                    "SELECT f.FlightID, f.Flight_Number, f.Departure_Time, f.Arrival_Time, f.Status, f.AircraftID, f.AirlineID, f.Departure_Airport_ID, f.Arrival_Airport_ID, " +
                    "dep.Code AS Departure, arr.Code AS Arrival, al.Name AS Airline, ac.Model AS Aircraft " +
                    "FROM Flight f " +
                    "JOIN Airport dep ON f.Departure_Airport_ID = dep.AirportID " +
                    "JOIN Airport arr ON f.Arrival_Airport_ID   = arr.AirportID " +
                    "JOIN Airline al  ON f.AirlineID  = al.AirlineID " +
                    "JOIN Aircraft ac ON f.AircraftID = ac.AircraftID");
                if (dgv.Columns.Contains("FlightID")) dgv.Columns["FlightID"].Visible = false;
                if (dgv.Columns.Contains("AircraftID")) dgv.Columns["AircraftID"].Visible = false;
                if (dgv.Columns.Contains("AirlineID")) dgv.Columns["AirlineID"].Visible = false;
                if (dgv.Columns.Contains("Departure_Airport_ID")) dgv.Columns["Departure_Airport_ID"].Visible = false;
                if (dgv.Columns.Contains("Arrival_Airport_ID")) dgv.Columns["Arrival_Airport_ID"].Visible = false;

                cmbAircraft.DataSource = dbHelper.ExecuteQuery("SELECT AircraftID, Model FROM Aircraft");
                cmbAircraft.DisplayMember = "Model"; cmbAircraft.ValueMember = "AircraftID";

                cmbAirline.DataSource = dbHelper.ExecuteQuery("SELECT AirlineID, Name FROM Airline");
                cmbAirline.DisplayMember = "Name"; cmbAirline.ValueMember = "AirlineID";

                DataTable dtAirports = dbHelper.ExecuteQuery("SELECT AirportID, Code + ' - ' + Name AS Info FROM Airport");
                cmbDepAirport.DataSource = dtAirports.Copy();
                cmbDepAirport.DisplayMember = "Info"; cmbDepAirport.ValueMember = "AirportID";
                
                cmbArrAirport.DataSource = dtAirports.Copy();
                cmbArrAirport.DisplayMember = "Info"; cmbArrAirport.ValueMember = "AirportID";
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["FlightID"]?.Value?.ToString();
            txtFlightNumber.Text = row.Cells["Flight_Number"]?.Value?.ToString();
            cmbStatus.Text = row.Cells["Status"]?.Value?.ToString();
            cmbAircraft.SelectedValue = row.Cells["AircraftID"]?.Value;
            cmbAirline.SelectedValue = row.Cells["AirlineID"]?.Value;
            cmbDepAirport.SelectedValue = row.Cells["Departure_Airport_ID"]?.Value;
            cmbArrAirport.SelectedValue = row.Cells["Arrival_Airport_ID"]?.Value;
            try { dtpDeparture.Value = Convert.ToDateTime(row.Cells["Departure_Time"]?.Value); dtpArrival.Value = Convert.ToDateTime(row.Cells["Arrival_Time"]?.Value); } catch { }
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Flight (Flight_Number, Departure_Time, Arrival_Time, Status, AircraftID, AirlineID, Departure_Airport_ID, Arrival_Airport_ID) " +
                           $"VALUES ('{txtFlightNumber.Text}','{dtpDeparture.Value:yyyy-MM-dd HH:mm}','{dtpArrival.Value:yyyy-MM-dd HH:mm}'," +
                           $"'{cmbStatus.Text}',{cmbAircraft.SelectedValue},{cmbAirline.SelectedValue},{cmbDepAirport.SelectedValue},{cmbArrAirport.SelectedValue})";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Flight added.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Flight SET Flight_Number='{txtFlightNumber.Text}', Departure_Time='{dtpDeparture.Value:yyyy-MM-dd HH:mm}', " +
                           $"Arrival_Time='{dtpArrival.Value:yyyy-MM-dd HH:mm}', Status='{cmbStatus.Text}', AircraftID={cmbAircraft.SelectedValue}, " +
                           $"AirlineID={cmbAirline.SelectedValue}, Departure_Airport_ID={cmbDepAirport.SelectedValue}, Arrival_Airport_ID={cmbArrAirport.SelectedValue} " +
                           $"WHERE FlightID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Flight updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this flight?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Flight WHERE FlightID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields()
        {
            txtId.Clear(); txtFlightNumber.Clear(); 
            if(cmbAircraft.Items.Count > 0) cmbAircraft.SelectedIndex = 0;
            if(cmbAirline.Items.Count > 0) cmbAirline.SelectedIndex = 0;
            if(cmbDepAirport.Items.Count > 0) cmbDepAirport.SelectedIndex = 0;
            if(cmbArrAirport.Items.Count > 0) cmbArrAirport.SelectedIndex = 0;
            cmbStatus.SelectedIndex = 0;
            dtpDeparture.Value = DateTime.Now; dtpArrival.Value = DateTime.Now;
        }
    }
}
