using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class PassengerForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtFirstName, txtLastName, txtPassport, txtEmail, txtNationality, txtPhone;
        private DateTimePicker dtpDOB;

        public PassengerForm()
        {
            FormTheme.Apply(this, "Manage Passengers");
            this.Size = new Size(860, 620);

            this.Controls.Add(FormTheme.MakeHeaderPanel("👤 Passengers", "Add, update, or remove passenger records", this.Width));

            // Grid
            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 820, 230);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            // Fields
            int lx = 15, fx = 130, lx2 = 430, fx2 = 545;
            int y = 325;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);


            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("First Name:", lx, y));
            txtFirstName = FormTheme.MakeTextBox(fx, y); this.Controls.Add(txtFirstName);
            this.Controls.Add(FormTheme.MakeLabel("Last Name:", lx2, y));
            txtLastName = FormTheme.MakeTextBox(fx2, y); this.Controls.Add(txtLastName);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Passport No:", lx, y));
            txtPassport = FormTheme.MakeTextBox(fx, y); this.Controls.Add(txtPassport);
            this.Controls.Add(FormTheme.MakeLabel("Email:", lx2, y));
            txtEmail = FormTheme.MakeTextBox(fx2, y, 260); this.Controls.Add(txtEmail);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Date of Birth:", lx, y));
            dtpDOB = FormTheme.MakeDatePicker(fx, y); this.Controls.Add(dtpDOB);
            this.Controls.Add(FormTheme.MakeLabel("Nationality:", lx2, y));
            txtNationality = FormTheme.MakeTextBox(fx2, y); this.Controls.Add(txtNationality);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Phone:", lx, y));
            txtPhone = FormTheme.MakeTextBox(fx, y); this.Controls.Add(txtPhone);

            // Buttons
            y += 50;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try
            {
                dgv.DataSource = dbHelper.ExecuteQuery(
                    "SELECT p.PassengerID, p.first_name, p.Last_name, p.Passport_No, p.email, " +
                    "CONVERT(varchar,p.date_of_birth,103) AS date_of_birth, p.Nationality, " +
                    "STRING_AGG(pp.Phone, ', ') AS Phones " +
                    "FROM Passenger p LEFT JOIN PassengerPhone pp ON p.PassengerID = pp.PassengerID " +
                    "GROUP BY p.PassengerID, p.first_name, p.Last_name, p.Passport_No, p.email, p.date_of_birth, p.Nationality");
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["PassengerID"]?.Value?.ToString();
            txtFirstName.Text = row.Cells["first_name"]?.Value?.ToString();
            txtLastName.Text = row.Cells["Last_name"]?.Value?.ToString();
            txtPassport.Text = row.Cells["Passport_No"]?.Value?.ToString();
            txtEmail.Text = row.Cells["email"]?.Value?.ToString();
            txtNationality.Text = row.Cells["Nationality"]?.Value?.ToString();
            txtPhone.Text = row.Cells["Phones"]?.Value?.ToString();
            try { dtpDOB.Value = Convert.ToDateTime(row.Cells["date_of_birth"]?.Value); } catch { }
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Passenger (first_name, Last_name, Passport_No, email, date_of_birth, Nationality) " +
                           $"VALUES ('{txtFirstName.Text}','{txtLastName.Text}','{txtPassport.Text}','{txtEmail.Text}'," +
                           $"'{dtpDOB.Value:yyyy-MM-dd}','{txtNationality.Text}');" +
                           $"DECLARE @id INT = SCOPE_IDENTITY();" +
                           $"IF '{txtPhone.Text}' <> '' INSERT INTO PassengerPhone VALUES (@id,'{txtPhone.Text}');";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Passenger added successfully.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Passenger SET first_name='{txtFirstName.Text}', Last_name='{txtLastName.Text}', " +
                           $"Passport_No='{txtPassport.Text}', email='{txtEmail.Text}', date_of_birth='{dtpDOB.Value:yyyy-MM-dd}', " +
                           $"Nationality='{txtNationality.Text}' WHERE PassengerID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Passenger updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this passenger?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Passenger WHERE PassengerID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields()
        {
            txtId.Clear(); txtFirstName.Clear(); txtLastName.Clear(); txtPassport.Clear();
            txtEmail.Clear(); txtNationality.Clear(); txtPhone.Clear(); dtpDOB.Value = DateTime.Today;
        }
    }
}
