using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class PaymentForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtBookingId, txtAmount;
        private DateTimePicker dtpPaymentDate;
        private ComboBox cmbMethod;

        public PaymentForm()
        {
            FormTheme.Apply(this, "Manage Payments");
            this.Size = new Size(820, 510);

            this.Controls.Add(FormTheme.MakeHeaderPanel("💳 Payments", "Track and manage booking payments", this.Width));

            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 780, 210);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            int lx = 15, fx = 130, lx2 = 450, fx2 = 565, y = 305;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Booking ID:", lx, y));
            txtBookingId = FormTheme.MakeTextBox(fx, y, 120); this.Controls.Add(txtBookingId);
            this.Controls.Add(FormTheme.MakeLabel("Amount:", lx2, y));
            txtAmount = FormTheme.MakeTextBox(fx2, y, 120); this.Controls.Add(txtAmount);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Payment Date:", lx, y));
            dtpPaymentDate = FormTheme.MakeDatePicker(fx, y, 180); this.Controls.Add(dtpPaymentDate);
            this.Controls.Add(FormTheme.MakeLabel("Method:", lx2, y));
            cmbMethod = FormTheme.MakeComboBox(fx2, y, 180);
            cmbMethod.Items.AddRange(new string[] { "Credit Card", "Debit Card", "Cash", "Bank Transfer", "Online" });
            cmbMethod.SelectedIndex = 0;
            this.Controls.Add(cmbMethod);

            y += 50;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try
            {
                dgv.DataSource = dbHelper.ExecuteQuery(
                    "SELECT p.PaymentID, p.BookingID, p.Amount, p.Payment_date, p.Payment_method, " +
                    "b.Status AS BookingStatus " +
                    "FROM Payment p JOIN Booking b ON p.BookingID = b.BookingID");
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["PaymentID"]?.Value?.ToString();
            txtBookingId.Text = row.Cells["BookingID"]?.Value?.ToString();
            txtAmount.Text = row.Cells["Amount"]?.Value?.ToString();
            cmbMethod.Text = row.Cells["Payment_method"]?.Value?.ToString();
            try { dtpPaymentDate.Value = Convert.ToDateTime(row.Cells["Payment_date"]?.Value); } catch { }
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Payment (BookingID, Amount, Payment_date, Payment_method) " +
                           $"VALUES ({txtBookingId.Text},{txtAmount.Text},'{dtpPaymentDate.Value:yyyy-MM-dd}','{cmbMethod.Text}')";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Payment recorded.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Payment SET BookingID={txtBookingId.Text}, Amount={txtAmount.Text}, " +
                           $"Payment_date='{dtpPaymentDate.Value:yyyy-MM-dd}', Payment_method='{cmbMethod.Text}' WHERE PaymentID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Payment updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this payment?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Payment WHERE PaymentID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields() { txtId.Clear(); txtBookingId.Clear(); txtAmount.Clear(); cmbMethod.SelectedIndex = 0; dtpPaymentDate.Value = DateTime.Today; }
    }
}
