using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace AirLine_Reservation_System.Forms
{
    public class TicketForm : Form
    {
        private DBHelper dbHelper = new DBHelper();
        private DataGridView dgv;
        private TextBox txtId, txtBookingId, txtFlightId, txtPassengerId, txtSeatNumber, txtPrice;
        private ComboBox cmbClass;

        public TicketForm()
        {
            FormTheme.Apply(this, "Manage Tickets");
            this.Size = new Size(860, 560);

            this.Controls.Add(FormTheme.MakeHeaderPanel("🎫 Tickets", "Manage issued flight tickets", this.Width));

            dgv = FormTheme.MakeGrid();
            dgv.Bounds = new Rectangle(15, 80, 820, 220);
            dgv.CellClick += Dgv_CellClick;
            this.Controls.Add(dgv);

            int lx = 15, fx = 130, lx2 = 450, fx2 = 565, y = 315;

            // ID is auto-generated by DB (IDENTITY). Hidden here — populated when a row is selected.
            txtId = new TextBox { Visible = false };
            this.Controls.Add(txtId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Booking ID:", lx, y));
            txtBookingId = FormTheme.MakeTextBox(fx, y, 100); this.Controls.Add(txtBookingId);
            this.Controls.Add(FormTheme.MakeLabel("Flight ID:", lx2, y));
            txtFlightId = FormTheme.MakeTextBox(fx2, y, 100); this.Controls.Add(txtFlightId);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Passenger ID:", lx, y));
            txtPassengerId = FormTheme.MakeTextBox(fx, y, 100); this.Controls.Add(txtPassengerId);
            this.Controls.Add(FormTheme.MakeLabel("Seat Number:", lx2, y));
            txtSeatNumber = FormTheme.MakeTextBox(fx2, y, 100); this.Controls.Add(txtSeatNumber);

            y += 38;
            this.Controls.Add(FormTheme.MakeLabel("Class:", lx, y));
            cmbClass = FormTheme.MakeComboBox(fx, y, 160);
            cmbClass.Items.AddRange(new string[] { "Economy", "Business", "First" });
            cmbClass.SelectedIndex = 0;
            this.Controls.Add(cmbClass);
            this.Controls.Add(FormTheme.MakeLabel("Price:", lx2, y));
            txtPrice = FormTheme.MakeTextBox(fx2, y, 120); this.Controls.Add(txtPrice);

            y += 48;
            var btnAdd = FormTheme.MakeButton("➕ Add", lx, y, FormTheme.BtnAdd);
            var btnUpdate = FormTheme.MakeButton("✏ Update", lx + 100, y, FormTheme.BtnUpdate);
            var btnDelete = FormTheme.MakeButton("🗑 Delete", lx + 200, y, FormTheme.BtnDelete);
            var btnClear = FormTheme.MakeButton("✖ Clear", lx + 300, y, FormTheme.BtnClear);
            btnAdd.Click += BtnAdd_Click;
            btnUpdate.Click += BtnUpdate_Click;
            btnDelete.Click += BtnDelete_Click;
            btnClear.Click += (s, e) => ClearFields();
            this.Controls.AddRange(new Control[] { btnAdd, btnUpdate, btnDelete, btnClear });

            LoadData();
        }

        private void LoadData()
        {
            try
            {
                dgv.DataSource = dbHelper.ExecuteQuery(
                    "SELECT t.TicketID, t.Seatnumber, t.Class, t.Price, t.BookingID, t.FlightID, t.PassengerID, " +
                    "p.first_name + ' ' + p.Last_name AS Passenger, f.Flight_Number " +
                    "FROM Ticket t " +
                    "JOIN Passenger p ON t.PassengerID = p.PassengerID " +
                    "JOIN Flight f    ON t.FlightID    = f.FlightID");
            }
            catch (Exception ex) { MessageBox.Show("Load error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void Dgv_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;
            DataGridViewRow row = dgv.Rows[e.RowIndex];
            txtId.Text = row.Cells["TicketID"]?.Value?.ToString();
            txtBookingId.Text = row.Cells["BookingID"]?.Value?.ToString();
            txtFlightId.Text = row.Cells["FlightID"]?.Value?.ToString();
            txtPassengerId.Text = row.Cells["PassengerID"]?.Value?.ToString();
            txtSeatNumber.Text = row.Cells["Seatnumber"]?.Value?.ToString();
            txtPrice.Text = row.Cells["Price"]?.Value?.ToString();
            cmbClass.Text = row.Cells["Class"]?.Value?.ToString();
        }

        private void BtnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                string q = $"INSERT INTO Ticket (Seatnumber, Class, Price, BookingID, FlightID, PassengerID) " +
                           $"VALUES ('{txtSeatNumber.Text}','{cmbClass.Text}',{txtPrice.Text},{txtBookingId.Text},{txtFlightId.Text},{txtPassengerId.Text})";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Ticket added.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnUpdate_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            try
            {
                string q = $"UPDATE Ticket SET Seatnumber='{txtSeatNumber.Text}', Class='{cmbClass.Text}', Price={txtPrice.Text}, " +
                           $"BookingID={txtBookingId.Text}, FlightID={txtFlightId.Text}, PassengerID={txtPassengerId.Text} WHERE TicketID={txtId.Text}";
                dbHelper.ExecuteNonQuery(q); LoadData(); ClearFields();
                MessageBox.Show("Ticket updated.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
        }

        private void BtnDelete_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtId.Text)) { MessageBox.Show("Select a row first."); return; }
            if (MessageBox.Show("Delete this ticket?", "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
            {
                try { dbHelper.ExecuteNonQuery($"DELETE FROM Ticket WHERE TicketID={txtId.Text}"); LoadData(); ClearFields(); }
                catch (Exception ex) { MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error); }
            }
        }

        private void ClearFields() { txtId.Clear(); txtBookingId.Clear(); txtFlightId.Clear(); txtPassengerId.Clear(); txtSeatNumber.Clear(); txtPrice.Clear(); cmbClass.SelectedIndex = 0; }
    }
}
